version: '3.7'

services:
  elasticsearch:
    build: 
      context: elasticsearch
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    build: 
      context: kibana
      args: 
        ELK_VERSION: $ELK_VERSION
    container_name: kibana
    ports:
      - 5601:5601
    depends_on: 
      - elasticsearch
    networks:
      - elk

  logstash:
    build: 
      context: logstash
      args: 
        ELK_VERSION: $ELK_VERSION
    container_name: logstash
    ports:
      - 5044:5044
      - 9600:9600
    volumes:
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    depends_on: 
      - elasticsearch
    networks:
      - elk
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    container_name: sql1
    ports:
      - 1433:1433
    volumes:
      - sqlvolume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass1234
    networks:
      - elk

networks: 
  elk:
    driver: bridge

volumes:
  sqlvolume: